server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    url: jdbc:postgresql://postgres:5432/customer
    username: 'okayreet'
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    enabled: false

#rabbitmq:
#  exchanges:
#    internal: customerExchange
#  queues:
#    notification: customerQueue
#  routing-keys:
#    internal-notification: customerRoutingKey